//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_LibraryEntities : DbContext
    {
        public db_LibraryEntities()
            : base("name=db_LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Authors> tbl_Authors { get; set; }
        public virtual DbSet<tbl_Books> tbl_Books { get; set; }
        public virtual DbSet<tbl_Categories> tbl_Categories { get; set; }
        public virtual DbSet<tbl_Employees> tbl_Employees { get; set; }
        public virtual DbSet<tbl_Members> tbl_Members { get; set; }
        public virtual DbSet<tbl_Movements> tbl_Movements { get; set; }
        public virtual DbSet<tbl_Penalties> tbl_Penalties { get; set; }
        public virtual DbSet<tbl_Safe> tbl_Safe { get; set; }
        public virtual DbSet<tbl_About> tbl_About { get; set; }
        public virtual DbSet<tbl_Communication> tbl_Communication { get; set; }
        public virtual DbSet<tbl_Messages> tbl_Messages { get; set; }
        public virtual DbSet<tbl_Announcement> tbl_Announcement { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
    }
}
