//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Penalties
    {
        public int ID { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<int> MOVEMENT { get; set; }
        public Nullable<System.DateTime> BEGINNING { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
        public Nullable<decimal> MONEY { get; set; }
    
        public virtual tbl_Members tbl_Members { get; set; }
        public virtual tbl_Movements tbl_Movements { get; set; }
    }
}
