//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Movements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Movements()
        {
            this.tbl_Penalties = new HashSet<tbl_Penalties>();
        }
    
        public int ID { get; set; }
        public Nullable<int> BOOK { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<int> EMPLOYEE { get; set; }
        public Nullable<System.DateTime> PURCHASE_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<bool> PROCESS { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
    
        public virtual tbl_Books tbl_Books { get; set; }
        public virtual tbl_Members tbl_Members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Penalties> tbl_Penalties { get; set; }
        public virtual tbl_Employees tbl_Employees { get; set; }
    }
}
