//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Books()
        {
            this.tbl_Movements = new HashSet<tbl_Movements>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<int> AUTHOR { get; set; }
        public string PRINTYEAR { get; set; }
        public string PUBLISHER { get; set; }
        public string PAGE { get; set; }
        public Nullable<bool> STATE { get; set; }
        public string IMAGE { get; set; }
    
        public virtual tbl_Authors tbl_Authors { get; set; }
        public virtual tbl_Categories tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Movements> tbl_Movements { get; set; }
    }
}
